# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Timon S. Gutleb
title: PhD student in applied mathematics
email: timon.gutleb@gmail.com
# website: www.github.com/sproogen/resume-theme

# Social links
twitter_username: TimonGutleb
github_username:  TSGut
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: gutleb
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
about_title:
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a PhD student of applied mathematics at Imperial College London, with a background in mathematics, physics and philosophy. I am also an associated student of the doctoral program “Dissipation and Dispersion in Nonlinear PDEs” through the University of Vienna.

  My research focus is on numerical analysis and the development of computational tools for PDEs, integral equations and fractional differential equations with an eye on applications in the natural sciences such as relativistic quantum mechanics.

# Projects Section
# projects_title: Projects

# More Section
more_title: Activities
more_content: | # this will include new lines to allow paragraphs
  <h2>Conference talks</h2>
   - 'A sparse spectral method for Volterra integral equations using orthogonal polynomials on the triangle', <a href="https://www.asc.tuwien.ac.at/rmmm2019/?open=program" target="_blank">RMMM 2019</a>, Vienna 2019.
   - 'A sparse spectral method for Volterra integral equations', <a href="https://numericalanalysisconference.org.uk/meetings/2019/minisymposia" target="_blank">28th Biennial Numerical Analysis Conference</a>, Glasgow 2019. <a href="https://github.com/TSGut/tsgut.github.io/raw/master/_files/Gutleb_NACONF2019_SparseSpectralVolterra_slides.pdf" target="_blank"><img src="https://img.shields.io/badge/slides-228B22.svg"/></a>
   - '<a href="https://github.com/TSGut/BProbeM" target="_blank">BProbeM</a>: a tool to measure matrix geometries', <a href="https://homepage.univie.ac.at/harold.steinacker/MM-ESI-homepage/index.html" target="_blank">Matrix Models for Noncommutative Geometry and String Theory</a>, Vienna 2018. <a href="https://github.com/TSGut/tsgut.github.io/raw/master/_files/Gutleb_ESI_workshop_BProbeM_slides.pdf" target="_blank"><img src="https://img.shields.io/badge/slides-228B22.svg"/></a>

  <h2>Event Organizing</h2>
  - Organizer for the 'Numerics of Schrödinger equations' minisymposium at <a href="https://www.asc.tuwien.ac.at/cmam2020/?open=minisymposia" target="_blank">CMAM-9 (2020)</a> with Hans-Peter Stimming.
  - <a href="https://www.damtp.cam.ac.uk/user/mjc249/home.html" target="_blank">Matthew Colbrook</a> and I are organizing a <a href="https://www.damtp.cam.ac.uk/seminars/cambridge-imperial-phds/" target="_blank">joint PhD seminar series (CICS)</a> between the University of Cambridge and Imperial College London centered around computational mathematics. Twice per term the seminar features PhD student talks from both departments as well as an invited plenary speaker.
  <h2>Teaching</h2>
  - Student tutor for Analysis 1 and 2 for Physicists, first year undergraduate calculus courses <a href="https://ufind.univie.ac.at/en/person.html?id=59491&teaching=true" target="_blank">(2015-2018)</a>, University of Vienna
  <h2>Scientific Outreach and Volunteering</h2>
  - Volunteer work for <a href="https://paleorxiv.github.io/" target="_blank">paleoarxiv</a> and the <a href="https://phylogenyexplorerproject.com/" target="_blank">Phylogeny Explorer</a> project (2018-2019)
  - Exhibition guide for the Austrian Academy of Sciences exhibit in celebration of 100 years of general relativity (2015)
  - Translator English → German for various educational platforms such as coursera.org and TED Talks (2015-2016)
  <h2>Some open science projects I want to share</h2>
    - The <a href="https://oeis.org/" target="_blank">On-Line Encyclopedia of Integer Sequences</a> (OEIS) is brilliant and incredibly useful for exploratory work in numerical analysis. I have tried to give back to it when and where possible (e.g. <a href="https://oeis.org/A334588" target="_blank">A334588</a>) and hope you will consider doing so as well!
    - <a href="https://www.primegrid.com/"  target="_blank">PrimeGrid</a> is a BOINC-based volunteer distributed computing project which searches for prime numbers of various sizes and with various interesting properties. The largest <a href="https://en.wikipedia.org/wiki/Primes_in_arithmetic_progression" target="_blank">AP-k</a> my computers have found so far has been <a href="https://www.primegrid.com/ap.php?userid=999250" target="_blank">my AP-27 of length 21</a> in 2018 - perhaps your devices will be luckier? 
    - I also share computing power with the BOINC-based distributed computing project <a href="https://boinc.bakerlab.org/rosetta/" target="_blank">Rosetta@home</a>, which works towards designing new proteins and predicting their 3-dimensional shapes, with potential biomedical applications.

# Education Section
# educaton_title: Education

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
